
name: Upload to cloudrun

on:
  workflow_call:

jobs:
  upload_to_cloudrun:

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - uses: 'google-github-actions/auth@v1'
      with:
        workload_identworkload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: 'taskman-hs-heilbronn-devsecops-tigers'
        image: 'ghcr.io/hs-heilbronn-devsecops-tigers/taskman:latest'
        env_vars: BACKEND=memory

