name: Hello World

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install pylint
        run: pip install pylint
      - name: Print Hello World
        run: pylint taskman