name: Main branch pipeline

on:
  workflow_dispatch:
  push:
    branches: ["main", "create_push_container"]

jobs:
  build:
    uses: ./.github/workflows/lint.yaml
  test:
    uses: ./.github/workflows/test.yaml
  security:
    permissions:
      security-events: write
    uses: ./.github/workflows/snyk.yaml
    secrets:
      snyk_token: ${{secrets.SNYK_TOKEN}}
  container:
    permissions:
      packages: write
    needs: ["build", "test", "security"]
    uses: ./.github/workflows/create-push-container.yaml
