name: Main branch pipeline

on:
  workflow_dispatch:
  push:
    branches: ["main", "cloudrun"]

jobs:
  build:
    uses: ./.github/workflows/lint.yaml
  test:
    uses: ./.github/workflows/test.yaml
  security:
    permissions:
      security-events: write
    uses: ./.github/workflows/snyk.yaml
    secrets:
      snyk_token: ${{secrets.SNYK_TOKEN}}
  container:
    permissions:
      packages: write
    needs: ["build", "test", "security"]
    uses: ./.github/workflows/create-push-container.yaml
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

  cloudrun:
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: ./.github/workflows/cloudrun.yaml
    needs: ["container"]
