name: Pull request build/test

on:
  workflow_dispatch:
  pull_request:
    types: [opened]

jobs:
  build:
    uses: ./.github/workflows/lint.yaml
  test:
    uses: ./.github/workflows/test.yaml
