name: Python package

on:
  pull_request:
    types: [opened]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install pylint
        run: python -m pip install pylint            
      - name: Install dependencies
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install development dependencies
        run: if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi      
      - name: Lint with pylint
        run: pylint taskman

  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install pytest
        run: python -m pip install pytest pytest-cov
      - name: Install dependencies
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install development dependencies
        run: if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi      
      - name: Test with pytest
        run: pytest --cov=taskman tests/